# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
  - cron: "2 1 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          chmod +x btt_writer_resource_update.sh
          ./btt_writer_resource_update.sh
      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          AWS_KEY_ID: "op://DevOps/cloudflare-r2-token/access-key-id"
          AWS_SECRET_ACCESS_KEY: "op://DevOps/cloudflare-r2-token/secret-access-key"
          ENDPOINT: "op://DevOps/cloudflare-r2-token/endpoint"
          
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ env.AWS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: writer-resources
          source_dir: 'index.sqlite'
          destination_dir: ''
          endpoint: ${{ env.ENDPOINT }}
      
